//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vmmsi.rc
//
#define IDI_PROGRAM_ICON                200

#define IDI_DEFAULT_LIGHT_MIC_MUTED     201
#define IDI_DEFAULT_LIGHT_MIC_UNMUTED   202
#define IDI_DEFAULT_LIGHT_MIC_ACTIVE    203
#define IDI_DEFAULT_DARK_MIC_MUTED      204
#define IDI_DEFAULT_DARK_MIC_UNMUTED    205
#define IDI_DEFAULT_DARK_MIC_ACTIVE     206

#define IDI_WIN10_LIGHT_MIC_MUTED       211
#define IDI_WIN10_LIGHT_MIC_UNMUTED     212
#define IDI_WIN10_LIGHT_MIC_ACTIVE      213
#define IDI_WIN10_DARK_MIC_MUTED        214
#define IDI_WIN10_DARK_MIC_UNMUTED      215
#define IDI_WIN10_DARK_MIC_ACTIVE       216

#define IDI_WIN11_LIGHT_MIC_MUTED       221
#define IDI_WIN11_LIGHT_MIC_UNMUTED     222
#define IDI_WIN11_LIGHT_MIC_ACTIVE      223
#define IDI_WIN11_DARK_MIC_MUTED        224
#define IDI_WIN11_DARK_MIC_UNMUTED      225
#define IDI_WIN11_DARK_MIC_ACTIVE       226

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
